### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by hferreira** [alx-ppv/ADS-delete-database#1]
I thing that you should run the close connections sql command before drop the database.

**Comment by sdarnell** [comment]
Yes, I also had this issue. FYI When I used:
```
ALTER DATABASE [DatabaseName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
```
I was able to complete the operation.

**Comment by alx-ppv** [comment]
Sorry for the late response.
@matan-levi updated the extension. 
Can you confirm that it works now? So I can close this issue.

**Comment by gabrielmaldi** [comment]
@alx-ppv I just tried this change and it works perfectly 👍🏻.

I had to clone the repo and build the .vsix with `vsce package` because the latest release 0.0.3 is from Aug 14, 2019.

Could you publish a new release which contains this change? Thanks!

I'll leave the .vsix I built here if someone wants to download it:
[deletedb-0.0.3.vsix.zip](https://github.com/alx-ppv/ADS-delete-database/files/5928879/deletedb-0.0.3.vsix.zip)
